[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true
verbosity = 2
ffi = true

remappings = [
  "forge-std=lib/forge-std/src",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

[profile.intense.fuzz]
runs = 10000
max_test_rejects = 999999

[fmt]
line_length = 160
number_underscore = "thousands"

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
polygon_pos = "https://polygon-mainnet.infura.io/v3/${INFURA_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon_pos = { key = "${POLYGONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config